# ESTE ES UN COMENTARIO QUE NO APARECE EN CONSOLA PARA WINDOWS

# VISUALIZAMOS QUE ARCHIVOS HAN SIDO CREADOS O MODIFICADOS Y AUN NO SE HAN SUBIDO A GIT
# LOS QUE NO SE HAN SUBIDO QUE HAN SIDO CREADOS O MODIFICADOS APARECERAN EN ROJO
# LOS QUE YA ESTAN SE SUBIERON AL REPOSITORIO LOCAL APARECEN EN VERDE
git status

# SE AGREGA TODOS LOS ARCHIVOS QUE SE HAN MODIFICADO Y SE SUBEN AL GIT
git add .

# SE CONFIGURAN CREDENCIALES PARA SUBIR
# SE CONFIGURA EL USERMAIL ASOCIADO AL GIT QUE SE VA A SUBIR
git config --global user.email "morales.gonzalez.pedroantonio@gmail.com"
# SE CONFIGURA EL USERNAME ASOCIADO AL GIT QUE SE VA A SUBIR
git config --global user.name "PedroAntonioKira"

# SE AGREGA UN COMENTARIO
git commit -m "Primera Prueba Completa para conexión con el resto del backend y apigateway parte 02"

# SUBE TODO EL PROYECTO A GITHUB
git push